### ISSUE TITLE
Design question - Tweaking neuron model to send payloads

### ISSUE THREAD

**Issue by louisblin** [SpiNNakerManchester/sPyNNakerNewModelTemplate#26]
Dear Maintainers,

I'm currently working on a Master's Thesis at Imperial College that focusses on alternative applications of SpiNNaker. Currently, I'm trying to implement Page Rank by creating a new model based on the neuron model ([here](https://github.com/louisblin/sPyNNaker8NewModelTemplate/tree/v4.0.0/c_models/src/neuron)), but it needs to send payloads in its MC packets.

My question is related to the design of such an implementation. In sPyNNaker's [`neuron/spike_processing.c`](https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/neuron/spike_processing.c#L162), `in_spikes_add_spike` adds incoming packets to a circular buffer. It seems the size of a `spike_t` is configurable in [`common/neuron-typedefs.h`](https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/common/neuron-typedefs.h#L30) to 64bits (key + payload), but the underlying circular buffer used in [`common/in_spikes.h`](https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/common/in_spikes.h#L5) only appears to take fixed-size 32bits integers.

Which approach would you recommend?
1. Maintain two separate buffers of keys / payloads in an alternative `common/in_spikes.h` implementation
2. Change the implementation spinn_common's [`circular_buffer.h`](https://github.com/SpiNNakerManchester/spinn_common/blob/master/include/circular_buffer.h#L19) to support `uint64_t` item.

Option 1 is maybe preferable as it keeps changes close to the model, plus it seems to be the design you chose in SpiNNFrontEndCommon's [`live_packet_gather.c`](https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/c_common/models/live_packet_gather/live_packet_gather.c#L22).

Thank you very much!

Best regards,
Louis

**Comment by rowleya** [comment]
If you know that every packet is 2 words, one easy option is to just add them one after the other, and then read them out in the same way.  This avoids the need to change anything at the lower level.

**Comment by louisblin** [comment]
Oh yes of course that would be even easier! And can event handlers be preempted as well? Otherwise I guess I would need to disable interrupts for the two lines that add the key and then the payload to the buffer.

**Comment by rowleya** [comment]
If you use the -1 callback for multicast packets, that cannot be interrupted by anything else, including another packet.

**Comment by louisblin** [comment]
Great, thank you very much @rowleya
