### ISSUE TITLE
Left over file that needs updating or removing?

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNakerNewModelTemplate#29]
Going over the documentation for new neuron models at the moment; it looks like https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/blob/master/python_models8/neuron/neuron_models/my_neuron_model_incl_input_and_threshold.py was an attempt to do what the my_full_neuron_impl does already (but possibly in a slightly different way).  This file isn't currently in line with the new implementation (and indeed doesn't have an equivalent in the C code structure at the moment) - so we need to decide whether we want to keep it and update it to match the new API (and add the necessary C code), or whether what this would do is too similar to the my_full_neuron_impl and therefore isn't necessary.  Thoughts?

**Comment by alan-stokes** [comment]
personally having only 1 API / example for the end users to work on i think is better than 2 which are only slightly different. but that's just my 2 pence

**Comment by andrewgait** [comment]
This was nuked yesterday by PR https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/50, so closing this.
