### ISSUE TITLE
Warnings when building C code

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNakerNewModelTemplate#51]
Currently the C code in here for the different impls (my_full_neuron_impl.h and my_neuron_impl_semd.h) builds fine, but with warnings, e.g.

> 
> In file included from <command-line>:
> /Users/andrewgait/work/spinnaker/git/sPyNNaker8NewModelTemplate/c_models/modified_src/my_models/implementations/my_full_neuron_impl.h:66:13: warning: ‘neuron_impl_do_timestep_update’ defined but not used [-Wunused-function]
>    66 | static bool neuron_impl_do_timestep_update(
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/andrewgait/work/spinnaker/git/sPyNNaker8NewModelTemplate/c_models/modified_src/my_models/implementations/my_full_neuron_impl.h:56:13: warning: ‘neuron_impl_add_inputs’ defined but not used [-Wunused-function]
>    56 | static void neuron_impl_add_inputs(
>       |             ^~~~~~~~~~~~~~~~~~~~~~
> /Users/andrewgait/work/spinnaker/git/sPyNNaker8NewModelTemplate/c_models/modified_src/my_models/implementations/my_full_neuron_impl.h:49:13: warning: ‘neuron_impl_store_neuron_parameters’ defined but not used [-Wunused-function]
>    49 | static void neuron_impl_store_neuron_parameters(
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/andrewgait/work/spinnaker/git/sPyNNaker8NewModelTemplate/c_models/modified_src/my_models/implementations/my_full_neuron_impl.h:42:13: warning: ‘neuron_impl_load_neuron_parameters’ defined but not used [-Wunused-function]
>    42 | static void neuron_impl_load_neuron_parameters(
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/andrewgait/work/spinnaker/git/sPyNNaker8NewModelTemplate/c_models/modified_src/my_models/implementations/my_full_neuron_impl.h:29:13: warning: ‘neuron_impl_initialise’ defined but not used [-Wunused-function]
>    29 | static bool neuron_impl_initialise(uint32_t n_neurons) {

I think this probably ought to be fixed by using .c files rather than .h files for impls, but open for suggestions.

**Comment by rowleya** [comment]
These can be disabled with a compiler directive before the function:
```
__attribute__((unused)) 
```

It looks like this is done in neuron_impl_standard.h but not in neuron_impl.h.  I am not sure if this can be used on a function declaration, but it is worth a go...
